development:
  host: 127.0.0.1
  username: WorkLaptop
  adapter: postgresql
  database: rails-weather_development
  encoding: unicode

 
production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
 